# Generated by Django 5.1.6 on 2025-02-15 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_moviedata_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviedata',
            name='image',
            field=models.ImageField(default='Images/None/NOimage.jpg', upload_to='Images/'),
        ),
    ]
